# Generated by Django 3.2.4 on 2021-09-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='op10',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='op5',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='op6',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='op7',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='op8',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='op9',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
